version: '2.4'

services:
  backend:
    extends:
      file: common.yml
      service: backend_base
    command: /commands/backend.sh
    depends_on:
      - redis

  celery_main:
    extends:
      file: common.yml
      service: backend_celery_base
    command: /commands/celery_main.sh
    depends_on:
      - redis

  redis:
    image: redis:6.2.1
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./mounts/redis_data:/data

  frontend:
    build: 
      dockerfile: ./compose/frontend/Dockerfile
      context: .
    image: frontend
    restart: unless-stopped

  nginx:
    build: 
      dockerfile: ./compose/nginx/Dockerfile
      context: .
    image: nginx
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
      - websocket
    ports:
      - 127.0.0.1:${HTTP_PORT}:80
    volumes:
      - ./mounts/uwsgi:/uwsgi
      - ./mounts/logs/nginx:/var/log/nginx
      - ./mounts/media:/webapp/media:ro
      - ./mounts/static:/webapp/static:ro

  websocket:
    build: 
      dockerfile: ./compose/websocket/Dockerfile
      context: .
    image: websocket
    restart: unless-stopped
    command: /commands/websocket.sh
    volumes:
      - ./mounts/uwsgi:/uwsgi
      - ./mounts/logs:/websocketapp/logs
      - ./mounts/db:/websocketapp/db
    env_file: .websocket.env
