# Generated by Django 3.2.8 on 2021-11-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocketAllowedOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='WebSocketCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=512)),
                ('callback_url', models.CharField(max_length=1024)),
                ('headers', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='WebSocketSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('code', models.CharField(blank=True, max_length=512, null=True)),
                ('dttm_added', models.DateTimeField(auto_now_add=True)),
                ('dttm_modified', models.DateTimeField(auto_now=True)),
                ('schema', models.TextField(default='{"type":"object"}')),
                ('method', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='WebSocketViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm', models.DateTimeField()),
                ('dttm_added', models.DateTimeField(auto_now_add=True)),
                ('dttm_modified', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('source', models.CharField(max_length=1024)),
                ('client', models.TextField()),
            ],
        ),
    ]
