# Generated by Django 3.2.8 on 2021-12-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websocketviolation',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
