# Generated by Django 3.2.8 on 2021-12-07 14:18

from django.db import migrations, models
import src.file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_added', models.DateTimeField(auto_now_add=True)),
                ('dttm_modified', models.DateTimeField(auto_now=True)),
                ('max_depth', models.IntegerField(blank=True, null=True)),
                ('max_size', models.IntegerField(blank=True, null=True)),
                ('size_mul', models.IntegerField(choices=[(1, 'byte'), (1024, 'KB'), (1048576, 'MB'), (1073741824, 'GB'), (1099511627776, 'TB')], default=1)),
                ('file_type', models.CharField(choices=[('xml', 'xml'), ('json', 'json'), ('pdf', 'pdf'), ('exe', 'exe'), ('zip', 'zip')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('file', models.FileField(upload_to=src.file.models.content_file_name)),
                ('dttm_loaded', models.DateTimeField(auto_now_add=True)),
                ('dttm_end_check', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('E', 'Ошибка'), ('P', 'В процессе'), ('O', 'Ок'), ('V', 'Нарушение')], default='P', max_length=1)),
                ('message', models.TextField(blank=True, null=True)),
                ('source', models.CharField(max_length=1024)),
                ('client', models.TextField()),
                ('file_type', models.CharField(default='Unknown', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='FilesProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_url', models.CharField(max_length=1024)),
                ('headers', models.TextField(default='{}')),
            ],
        ),
    ]
