# Generated by Django 3.2.8 on 2021-11-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('name', models.CharField(max_length=1024)),
                ('file', models.FileField(upload_to='files')),
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('E', 'Ошибка'), ('P', 'В процессе'), ('O', 'Ок')], default='P', max_length=1)),
                ('message', models.TextField(blank=True, null=True)),
                ('source', models.CharField(max_length=1024)),
                ('client', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FilesProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_url', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='HTTPAllowedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('code', models.CharField(max_length=512)),
                ('dttm_added', models.DateTimeField(auto_now_add=True)),
                ('dttm_modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=64)),
            ],
        ),
    ]
